### PR TITLE
merging

### PR DESCRIPTION
**Pull request by gvgvgvijayan**
merging

### CODE REVIEW

**Comment by gvgvgvijayan** [comment]
merging

**Comment by aleron75** [comment]
Hi, thank you for your contribution.

Please, change

* http://www.ecommercegorilla.com/how-to-set-up-multiple-store-fronts-with-magento/ 

into

* http://www.ecommercegorilla.com/category/magento-e-commerce-platform/

and put the following:

* http://www.ecommercegorilla.com/category/magento-e-commerce-platform/
* http://tutorialmagento.com/

under the "Quickies and Tutorials" section.

Best regards,
Alessandro

**Comment by aleron75** [comment]
Hi @gvgvgvijayan, any news about proposed changes?

**Comment by gvgvgvijayan** [comment]
@aleron75 Sorry for very late reply now only I saw your suggestion

**Pull request merged**
