### PR TITLE
Update resources.csv

### PR DESCRIPTION
**Pull request by licentia**
Added new extension

### CODE REVIEW

**Comment by aleron75** [comment]
Helo @licentia 
sorry but the https://github.com/licentia/panda URL doesn't exist

**Comment by licentia** [comment]
@aleron75  is it public now.

**Comment by aleron75** [comment]
In the spirit of Mageres, I would use "Green Flying Panda Extension"  as the title and "This extension integrates Magento with Green Flying Panda sales automation tool".

Please consider applying this change. Otherwise, I will be willing to do it for you soon.

Thanks for your contribution!

**Comment by licentia** [comment]
Hi @aleron75,

>"This extension integrates Magento with Green Flying Panda sales automation tool" 

This is an isolated extension and does not integrate into a service. You can change the description, but I think users will perceive they have to subscribe to something to use the extension.

Regards

**Comment by aleron75** [comment]
Sorry @licentia, it's my fault. I didn't get that the service is all in the extension. So my suggestion is to keep the current description and set "Green Flying Panda Sales Automation" as the title. What do you think?

**Comment by licentia** [comment]
@aleron75 sounds perfect to me! 

Thanks!

**Comment by aleron75** [comment]
Will you update the PR?

**Comment by licentia** [comment]
Sorry @aleron75 

Was not paying attention to what I was doing, so I ended up creating a new PR.

**Pull request closed without merging**
