### PR TITLE
Update resources.csv

### PR DESCRIPTION
**Pull request by socialresponse**
Please add our recources

### CODE REVIEW

**Comment by aleron75** [comment]
Hello @socialresponse thanks for your contribution.
Can you please help me understand what this extension is about? I don't get it from the README.

**Comment by socialresponse** [comment]
hi @aleron75 , this is an extension that brings intro js into magento and lets you manipulate it from the admin Panel. It lets people create a guided tour through their site with little to no setup of the code.

**Comment by aleron75** [comment]
Thanks for the explanation, it will be useful when I'll send the monthly recap newsletter :+1:

**Comment by socialresponse** [comment]
Thank you!

**Pull request merged**
