### PR TITLE
add mage-one.com

### PR DESCRIPTION
**Pull request by Flyingmana**
as the eol for Magento1 becomes a more prominent topic in several Blogs, I think its worth to note Companies who offer paid security support for it after it is running out of official support.

disclaimer:
Iam not affiliated to the company, but know the people behind it and trust them on this topic.

### CODE REVIEW

**Comment by aleron75** [comment]
Hi, the problem I see with this kind of resources is that, to be inclusive, we should list every company that offers similar service and at that point, the list would become a directory of service companies, that's not the intent of MageRes.
What do you think?

**Comment by Flyingmana** [comment]
In my experience companies which provide such services in a professional and dedicated manner are quite rare. For example I only heard of one Company who did offer paid security support and patches for outdated versions of PHP.

PHP is used a lot more then Magento, so I expect to see here similar only very few who do offer security support for Magento itself.
I see this different then to offer security support for Shops in general, like many agencies do.
I understand, this may still not be the best or right place for it. But I would not know where to collect this informations else.

**Comment by aleron75** [comment]
Ok I trust your judgment, only one thing to accept the PR: please update the `resources.csv` file and regenerate the `README.md` file instead of manually changing it.
Thanks

**Comment by aleron75** [comment]
Perfect, thank you!

**Pull request merged**
